### ISSUE TITLE
Player misplaced when exiting non-ground level doors at higher terrain altitudes

### ISSUE THREAD

**Issue by ajrb** [Interkarma/daggerfall-unity#1606]
**Description**
For buildings with non ground level doors at higher terrain altitudes (I think it's altitude - it happens in Wrothgardian Mountains and not in Daggerfall) if an interior save is loaded and the player uses the door, they're placed at ground level which is actually inside the building geometry. I found the problem with my upcoming new location, but have successfully reproduced it with the current code and a vanilla location.

**To Reproduce**
1. Go to Hollech in Wrothgarian Mountains region.
2. Ensure you are member of DB (guildjoin DarkBrotherHood) and enter the hall.
3. Save next to one of the upper doors that lead outside.
4. Load that save and click the door.

I have a savefile at point 4 to demo this.
[SAVE185.zip](https://github.com/Interkarma/daggerfall-unity/files/3827599/SAVE185.zip)

**Expected behavior**
Be placed on top of the building rather than inside.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Latest master branch

**Additional context**
I have tried to figure out what the issue is, but it's connected to the world compensation stuff in StreamingWorld and I don't understand how it is supposed to work. Going to need this to be looked at by you @Interkarma - sorry. What I have found is that StreamingWorld.RepositionPlayer method calculates the y to set the player transform to to be 1000+ way up in the air. (world compensation is 0 at this point since outside world is being built) Something must then snap the player to the terrain, but I couldn't find out what. This puts the player inside the building geometry which unfortunately in my new quest is a set of stairs that traps the player.

**Comment by Interkarma** [comment]
This sounds like a duplicate of #1380. I believe it's just a load order issue, but still nontrivial to correct. I've been meaning to take another look at this for a while.

**Comment by ajrb** [comment]
Ah, yes, so it is a duplicate of #1380. This does have more details, and a savefile though. :)

**Comment by Interkarma** [comment]
Yeah, this is definitely a more detailed report. I'll close the older reminder to myself.

**Comment by Interkarma** [comment]
This should be resolved by #1655. I had actually tried this solution earlier, but didn't realise world suppression was still happening in code despite setting property on StreamingWorld. Thanks to @df-ferital for identifying.

**Comment by df-ferital** [comment]
I just checked and it is not fixed, the player is still placed at ground level when exiting the Dark Brotherhood building from the first floor. Unfortunately, I don't have time to investigate further at the moment.

**Comment by Interkarma** [comment]
My test cases were resolved, so likely multiple causes then. I'll reopen and take another look later.

**Comment by df-ferital** [comment]
I see, I also suspected this was due to this particular building configuration with multiple exits.

**Comment by petchema** [comment]
Just checked, and it still exists with current dev/0.10.18 (as probably expected)
![exit 2nd floor](https://user-images.githubusercontent.com/1211431/72467619-95dee600-37db-11ea-81cd-d67b89a490ae.jpg)
[SAVE519.zip](https://github.com/Interkarma/daggerfall-unity/files/4067304/SAVE519.zip)

**Comment by ajrb** [comment]
And FWIW I found this still happening occasionally when exiting the fort for MountainRumors quest in 0.11.0

**Comment by Interkarma** [comment]
I haven't been able to reproduce any regressions after testing all the edge cases I can think of. Will close this one now.
