### ISSUE TITLE
0.13.5: Daggerfall directory impossible to select on Linux

### ISSUE THREAD

**Issue by ahouts** [Interkarma/daggerfall-unity#2309]
**Describe the bug**
The root directory is not displayed in the drive list on Linux when selecting the Daggerfall game files during setup.

**To Reproduce**
1. Launch Daggerfall Unity

**Expected behavior**
The root directory `/` should always be an option on Unix-like operating systems (macOS, Linux). Due to the unified directory tree this will be sufficient to locate any path, unlike Windows which has a concept of drives.

It seems that Unity only detects my boot partition and some virtual drives on my system. As amusing as it would be to install Daggerfall on my boot partition, that seems impractical.

**Screenshots**
![Screenshot_2022-04-18_23-21-15](https://user-images.githubusercontent.com/16907671/163920414-6128c31c-7247-4b87-ad99-225e90d33c77.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: 2022-04-18

**Additional context**

**Comment by Interkarma** [comment]
Please use the forums for personal support.

https://forums.dfworkshop.net/

Many of our users and a few of the devs are playing on Linux and they should be able to provide some assistance.

**Comment by ahouts** [comment]
I wouldn't describe this as a support issue. Using `Directory.GetLogicalDrives()` to find filesystem roots on Linux or macOS doesn't make sense considering there is only one possible root, and it has nothing to do with filesystems or disks.

**Comment by ahouts** [comment]
[Wrote a fix for anyone who finds this in the future.](https://github.com/ahouts/daggerfall-unity/compare/master...ahouts:do-not-attempt-to-list-drives-on-unix)

**Comment by Interkarma** [comment]
I'm sorry, I wasn't trying to be difficult. Just that root displays fine in my Linux test environment (Ubuntu) and nobody has raised this before in the 5+ years DFU has had Linux builds. I can only imagine it's something specific to your environment?

![image](https://user-images.githubusercontent.com/10426244/164127042-f6c8e482-fd4e-4420-8977-da7008670442.png)

The forums are the best place to nail down individual support problems like this. Other Linux users in the community can offer support and feedback. If there is a problem that needs to be addressed in DFU, then it can be escalated to an Issue and fixed on our end once we have more understanding of problem.

**Comment by ahouts** [comment]
Fair enough, guess my point is that this function doesn't even make sense outside of windows and it doesn't surprise me it gives bad results. Taking a look at the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getlogicaldrives?view=net-6.0):
```
Retrieves the names of the logical drives on this computer in the form "<drive letter>:\".
```
It seems they try to emulate this idea on Unix despite the fact it doesn't really make sense. I'm using zfs, which probably doesn't work with whatever method Microsoft is using to enumerate filesystems.

**Comment by Interkarma** [comment]
That sounds likely. Well, your fix linked above looks low-impact and I can't imagine it would cause any issues. I'm happy to integrate that into core and credit you for fix.

I'll reopen this one and go from there.

**Comment by petchema** [comment]
Don't know if they use the same code, but Mono seems to try to parse /proc/self/mountinfo, with /proc/mounts as a fallback
https://github.com/mono/mono/blob/main/mono/metadata/w32file-unix.c#L3987
I suspect something breaks their parsers expectations; Either way, the workaround looks fine

**Comment by d10sfan** [comment]
@Interkarma I'm seeing this as well when attempting to run the game inside Linux steam. Best example is the new daggerfall steam that just came out - https://store.steampowered.com/app/1812390/The_Elder_Scrolls_II_Daggerfall

I imagine that the above fix would also fix it for this as well.

**Comment by lavadrop** [comment]
I installed DFU on my openSUSE installation using the Steam data files, so I think the issue was resolved.

**Comment by d10sfan** [comment]
I think it's different on different environments. I still see this like I mentioned above
